// Bundles src/charts.tsx (React + Nivo) into one minified IIFE and writes it,
// as a string, to packages/core/dashboard/charts-bundle.ts: a plain relative
// module, so the plugin and the CLI import it without installing anything.
//
//   npm --prefix packages/charts ci && npm --prefix packages/charts run build

import { build } from 'esbuild'
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const here = new URL('.', import.meta.url)
const out = fileURLToPath(new URL('../core/dashboard/charts-bundle.ts', here))
const pkg = JSON.parse(readFileSync(new URL('package.json', here), 'utf8'))

const result = await build({
  entryPoints: [fileURLToPath(new URL('src/charts.tsx', here))],
  bundle: true,
  minify: true,
  format: 'iife',
  target: 'es2020',
  jsx: 'automatic',
  // Not the repository's tsconfig: that one is the mods engine's, whose JSX factory is `h`.
  tsconfigRaw: { compilerOptions: { jsx: 'react-jsx' } },
  legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"' },
  write: false,
})

// The bundle is inlined into a <script> block: nothing in it may end the block or open a comment.
const code = result.outputFiles[0].text.replace(/<\/(script)/gi, '<\\/$1').replace(/<!--/g, '<\\!--')

const versions = Object.entries(pkg.devDependencies)
  .filter(([n]) => n !== 'esbuild')
  .map(([n, v]) => `${n}@${v}`)
  .join(', ')
writeFileSync(
  out,
  `// @generated by packages/charts/build.mjs from packages/charts/src/charts.tsx. Do not edit.
// ${versions}. ${Math.round(code.length / 1024)} KB.

/** The dashboard's chart bundle: inlined into a page that has a [data-chart] mount. */
export const CHARTS_JS = ${JSON.stringify(code)}
`,
)
console.log(`Wrote ${fileURLToPath(new URL('../core/dashboard/charts-bundle.ts', here))} (${Math.round(code.length / 1024)} KB)`)
